# Generated by Django 3.1.2 on 2022-06-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeUploadsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumeTitle', models.CharField(max_length=255, verbose_name='Resume Name')),
                ('resumeFile', models.FileField(upload_to='Docs', verbose_name='Resume File')),
                ('resumeDateTime', models.DateTimeField(verbose_name='Upload DateTime')),
                ('resumeActive', models.BooleanField(default=False, verbose_name='Resume Active')),
            ],
        ),
    ]
