# Generated by Django 3.1.2 on 2022-06-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_resumeuploadslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeuploadslist',
            name='resumeDateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='Upload DateTime'),
        ),
    ]
