# Generated by Django 3.1.2 on 2022-06-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_auto_20220620_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesIndexList',
            fields=[
                ('servID', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Service No')),
                ('servHead', models.CharField(max_length=1000, verbose_name='Service Title')),
                ('servClassIcon', models.CharField(max_length=1000, verbose_name='Class Name')),
                ('servDescr', models.TextField(verbose_name='Service Description')),
            ],
        ),
    ]
