# Generated by Django 3.1.2 on 2022-06-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_servicesindexlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsList',
            fields=[
                ('testMonID', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Testimonial ID')),
                ('testMonTitle', models.CharField(max_length=1000, verbose_name='Testimonial Title')),
                ('testMonImage', models.ImageField(upload_to='Images/Testimonials')),
                ('testMonDescr', models.TextField(verbose_name='Testimonial Description')),
            ],
        ),
    ]
