# Generated by Django 3.1.2 on 2022-06-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_testimonialslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSkillsList',
            fields=[
                ('tSkillId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Skills ID')),
                ('tSkillTitle', models.CharField(max_length=1000, verbose_name='Skills Title')),
                ('tSkillPercent', models.IntegerField(verbose_name='Skills Percent')),
                ('tSkillActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='testimonialslist',
            name='testMonImage',
            field=models.ImageField(upload_to='Images/Testimonials', verbose_name='Testimonial Images'),
        ),
    ]
