# Generated by Django 3.1.2 on 2022-06-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_auto_20220624_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsList',
            fields=[
                ('blID', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Blogs ID')),
                ('blTitle', models.CharField(max_length=1000, verbose_name='Blogs Title')),
                ('blCommentsNo', models.IntegerField(verbose_name='Blogs Comment No.')),
                ('blImages', models.ImageField(upload_to='Images/Blogs', verbose_name='Blogs Image')),
                ('blDescr', models.TextField(max_length=2000, verbose_name='Blogs Description')),
                ('blAuthor', models.CharField(max_length=1000, verbose_name='Blogs Author')),
                ('blPublishedDate', models.DateField(verbose_name='Blogs Published Date')),
                ('blActive', models.BooleanField(default=False, verbose_name='Blogs Active')),
            ],
        ),
        migrations.AlterField(
            model_name='technicalskillslist',
            name='tSkillActive',
            field=models.BooleanField(default=False, verbose_name='Skills Active'),
        ),
    ]
