# Generated by Django 3.1.2 on 2022-06-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_auto_20220624_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogslist',
            name='blPublishedDate',
            field=models.DateField(verbose_name='Blogs Published Date'),
        ),
    ]
