# Generated by Django 3.1.2 on 2022-06-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_auto_20220624_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogslist',
            name='blPublishedDay',
            field=models.CharField(max_length=100, verbose_name='Blogs Published Day'),
        ),
        migrations.AlterField(
            model_name='blogslist',
            name='blPublishedMonth',
            field=models.CharField(max_length=100, verbose_name='Blogs Published Month'),
        ),
        migrations.AlterField(
            model_name='blogslist',
            name='blPublishedYear',
            field=models.CharField(max_length=100, verbose_name='Blogs Published Year'),
        ),
    ]
