# Generated by Django 3.1.2 on 2022-06-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0012_auto_20220624_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogslist',
            name='blPublishedDay',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=100, verbose_name='Blogs Published Day'),
        ),
        migrations.AlterField(
            model_name='blogslist',
            name='blPublishedMonth',
            field=models.CharField(choices=[('1', 'Jan'), ('2', 'Feb'), ('3', 'Mar'), ('4', 'Apr'), ('5', 'May'), ('6', 'Jun'), ('7', 'Jul'), ('8', 'Aug'), ('9', 'Sep'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], max_length=100, verbose_name='Blogs Published Month'),
        ),
    ]
