# Generated by Django 3.1.2 on 2022-06-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0013_auto_20220624_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeuploadslist',
            name='resumeDateTime',
            field=models.DateTimeField(verbose_name='Upload DateTime'),
        ),
    ]
