# Generated by Django 3.1.2 on 2022-06-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0014_auto_20220628_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesindexlist',
            name='servActive',
            field=models.BooleanField(default=False, verbose_name='Service Active'),
        ),
    ]
